// Hand-authored ambient types for the harness config `.typescript-ai-harness.json`
// — the CORE, owned by GEN-002: the generic, domain-blind spine every config
// block satisfies, plus the envelope. This file names no namespace and no
// block; those are declaration-merged in by each block ADR's fence in
// `harness-config-extension.d.ts`. GEN-002's rules type-reference ONLY this
// file. Compile-time only — erased at runtime, so it never violates archgate's
// no-imports constraint. rules.d.ts is @generated by archgate — never add
// types there. Type ↔ validator alignment is a manual review duty (GEN-002)
// until the real-binary gate in #9.
declare namespace Harness {
  /** Policy for files a block's pathRules never claim. Default: 'exempt'. */
  type Unmatched = 'exempt' | 'error';
  /** The tier a pathRules entry's violations emit at. Default: 'error'. */
  type EntryTier = 'error' | 'warning';

  /** A set of files by glob arithmetic: glob(include) − glob(exclude). */
  interface FileSet {
    /** Non-empty array of non-empty globs, relative to the repo root. */
    include: string[];
    /** Files matched here fall OUTSIDE the set — for a pathRules entry that
     * means fall-through to later entries, never an exempt claim. */
    exclude?: string[];
  }

  /** One ordered pathRules entry. First matching entry claims a file. */
  interface PathRule<TRule = Record<string, unknown>> extends FileSet {
    /** true ⇒ claim matched files and waive the block's policy for them.
     * An exempt entry MUST NOT carry `rule` or `severity`. */
    exempt?: boolean;
    severity?: EntryTier;
    /** Block-owned policy payload — opaque to the spine; schema and
     * interpretation belong to the block's owning ADR. Absent = an open
     * governed entry (the block's baseline policy applies). */
    rule?: TRule;
  }

  /** The generic shape every config block satisfies, exactly two key levels
   * deep: `{ version, [namespace]: { [block]: ConfigBlock } }`. */
  interface ConfigBlock<TRule = Record<string, unknown>, TSettings = Record<string, unknown>> {
    unmatched?: Unmatched;
    /** The governed universe for `unmatched: 'error'` — present iff that
     * posture is declared. Files in coverage claimed by no entry are
     * violations, raised by the block owner at the error tier. */
    coverage?: FileSet;
    /** Block-owned block-level knobs — opaque to the spine. */
    settings?: TSettings;
    pathRules: PathRule<TRule>[];
  }

  /** The envelope. `version` — a semver string exactly matching the installed
   * harness release (`package.json` `.version`) — is the only key GEN-002
   * knows by name; namespaces and their blocks are declaration-merged in by
   * block ADRs' fences in `harness-config-extension.d.ts`. */
  interface Config {
    version: string;
  }
}
