// Hand-authored ambient types for the harness config `.typescript-ai-harness.json`.
// Shared authoring aid for GEN-002 (the spine) and every block owner (GEN-003, …):
// rules files reference it via `/// <reference path="../harness-config.d.ts" />`
// beside their rules.d.ts reference. Compile-time only — erased at runtime, so it
// never violates archgate's no-imports constraint. rules.d.ts is @generated by
// archgate — never add types there. Type ↔ validator alignment is a manual review
// duty (GEN-002) until the real-binary gate in #9.
declare namespace Harness {
  // ── Spine — owned by GEN-002 ─────────────────────────────────────────────
  /** Policy for files a block's pathRules never claim. Default: 'exempt'. */
  type Unmatched = 'exempt' | 'error';
  /** The tier a pathRules entry's violations emit at. Default: 'error'. */
  type EntryTier = 'error' | 'warning';

  /** A set of files by glob arithmetic: glob(include) − glob(exclude). */
  interface FileSet {
    /** Non-empty array of non-empty globs, relative to the repo root. */
    include: string[];
    /** Files matched here fall OUTSIDE the set — for a pathRules entry that
     * means fall-through to later entries, never an exempt claim. */
    exclude?: string[];
  }

  /** One ordered pathRules entry. First matching entry claims a file. */
  interface PathRule<TRule = Record<string, unknown>> extends FileSet {
    /** true ⇒ claim matched files and waive the block's policy for them.
     * An exempt entry MUST NOT carry `rule` or `severity`. */
    exempt?: boolean;
    severity?: EntryTier;
    /** Block-owned policy payload — opaque to the spine; schema and
     * interpretation belong to the block's owning ADR. Absent = an open
     * governed entry (the block's baseline policy applies). */
    rule?: TRule;
  }

  /** The generic shape every registered path-scoped block satisfies. */
  interface ConfigBlock<TRule = Record<string, unknown>, TSettings = Record<string, unknown>> {
    unmatched?: Unmatched;
    /** The governed universe for `unmatched: 'error'` — present iff that
     * posture is declared. Files in coverage claimed by no entry are
     * violations, raised by the block owner at the error tier. */
    coverage?: FileSet;
    /** Block-owned block-level knobs — opaque to the spine. */
    settings?: TSettings;
    pathRules: PathRule<TRule>[];
  }

  // ── markdown.frontmatter payload — owned by GEN-003 ──────────────────────
  /** Per-entry frontmatter policy (the floor's per-path knobs). */
  interface FrontmatterRule {
    /** Closed set of kebab-case types the entry accepts; absent = open. */
    allowedTypes?: string[];
    /** Pins which label key matched files must carry; absent = either, exactly one. */
    label?: 'name' | 'title';
    requireDescription?: boolean;
    /** Cap overrides; defaults 64 / 1024 / 30. */
    maxLabel?: number;
    maxDescription?: number;
    maxTag?: number;
  }
  interface FrontmatterSettings {
    /** true ⇒ any governed file may declare `type: draft` regardless of its
     * entry's allowedTypes; the rest of the floor still applies. */
    draftEscape?: boolean;
  }

  /** The whole config file. Top-level keys outside `markdown` are free — the
   * consumer-extension surface for project-local governance (GEN-002 §2). */
  interface Config {
    markdown?: {
      /** Config format version stamp (currently 1). Reserved key, not a block. */
      version: number;
      frontmatter?: ConfigBlock<FrontmatterRule, FrontmatterSettings>;
    };
    [key: string]: unknown;
  }
}
