// Hand-authored per-block EXTENSIONS of the harness-config core types — the
// config's block registry. Each block ADR owns exactly one fence:
//
//   // <ADR-ID>-START: <namespace.block>
//   …the block's payload types, its namespace interface, and a Config
//   declaration-merge attaching the namespace…
//   // <ADR-ID>-END
//
// GEN-002 owns the fence GRAMMAR: balanced
// markers, no nesting or overlap, each START declaring one well-formed
// `namespace.block` path, unique across fences. The union of declared paths
// is the config's closed set of legal keys — GEN-002's shape rule reads it at
// check time, so a config key with no declaring fence is an error, never a
// silent fall-back. Each block ADR owns its fence CONTENTS wholesale. Adding
// a block = adding a fence here plus an owning ADR; GEN-002 is never amended.
// rules.d.ts is @generated by archgate — never add types there.
/// <reference path="./harness-config-core.d.ts" />
declare namespace Harness {
  // GEN-003-START: markdown.frontmatter
  /** Per-entry frontmatter policy (the floor's per-path knobs). */
  interface FrontmatterRule {
    /** Closed set of kebab-case types the entry accepts; absent = open. */
    allowedTypes?: string[];
    /** Pins which label key matched files must carry; absent = either, exactly one. */
    label?: 'name' | 'title';
    requireDescription?: boolean;
    /** Cap overrides; defaults 64 / 1024 / 30. */
    maxLabel?: number;
    maxDescription?: number;
    maxTag?: number;
  }
  interface FrontmatterSettings {
    /** true ⇒ any governed file may declare `type: draft` regardless of its
     * entry's allowedTypes; the rest of the floor still applies. */
    draftEscape?: boolean;
  }
  /** The `markdown` namespace of the config, introduced by this fence —
   * named interfaces so further markdown blocks can declaration-merge in. */
  interface Markdown {
    frontmatter?: ConfigBlock<FrontmatterRule, FrontmatterSettings>;
  }
  interface Config {
    markdown?: Markdown;
  }
  // GEN-003-END
}
