import type { Action, Integration } from '../../types';
import { ARCHGATE_DEP, archgateConfig, claudeSettingsLocal, RULES_DTS_IGNORE } from './template';

/**
 * archgate is a **hybrid** Integration, split on the `--yes` flag (ADR-0005):
 *
 * - Interactive (no `--yes`): shell out to `npx archgate init`. A human is
 *   present, so archgate drives its own onboarding — editor prompt, plugin login
 *   + global `~/.claude` install, example ADR — the full native experience.
 * - Headless (`--yes`): archgate exposes no non-interactive `init` (a TTY reopens
 *   the prompt, and it mutates global state), so we write a controlled snapshot
 *   directly. The seeded config and Claude settings are Seeded config files
 *   (write-if-absent); an empty `.archgate/adrs/` (kept with `.gitkeep`) makes
 *   `archgate check` recognise the workspace and pass with zero ADRs — that
 *   directory, not `config.json`, is the marker `check` keys off. `rules.d.ts` is
 *   regenerated by `archgate check` (the first step of `verify`) and only
 *   gitignored. No example ADR, no `lint/` placeholder, no plugin install; a
 *   one-line post-run note points to `archgate plugin install` (US-13).
 *
 * Either way the Dependency is version-pinned so `check` behaviour matches the
 * snapshot the headless path is captured against.
 */
export const archgate: Integration = {
  id: 'archgate',
  label: 'archgate — deterministic ADR governance',
  devDependencies: [ARCHGATE_DEP],

  plan(ctx) {
    const install: Action = { kind: 'installDeps', dev: [...this.devDependencies] };
    if (!ctx.yes) {
      // Interactive: let archgate own its own onboarding. Emitted before husky
      // (registry order) so `archgate init` runs ahead of `npx husky`.
      return [install, { kind: 'runCommand', command: 'npx', args: ['archgate', 'init'] }];
    }
    return [
      install,
      { kind: 'writeFile', path: '.archgate/config.json', contents: archgateConfig(), overwrite: false },
      { kind: 'writeFile', path: '.claude/settings.local.json', contents: claudeSettingsLocal(), overwrite: false },
      // Seed an empty adrs/ dir (no example ADR — US-9) so `archgate check` sees an
      // initialised workspace; .gitkeep keeps the dir under git for CI.
      { kind: 'writeFile', path: '.archgate/adrs/.gitkeep', contents: '', overwrite: false },
      { kind: 'appendLines', path: '.gitignore', lines: RULES_DTS_IGNORE },
    ];
  },
};
