import { ARCHGATE_VERSION, HARNESS_VERSION } from '../../harness-config';

/**
 * The `archgate init --editor claude` snapshot, captured against the pinned
 * version (ADR-0005). archgate exposes no non-interactive `init`, so rather than
 * shell out we emit this surface directly — a `--yes` run then stays headless
 * and controlled. When bumping the pin, re-capture the snapshot and change
 * `ARCHGATE_VERSION` in `harness.config.json` (its single source — the Harness
 * build config, ADR-0010 §2).
 */

/**
 * The pinned archgate version, re-exported from the Harness build config so the
 * snapshot has a named coupling point. The Dependency is pinned rather than
 * installed latest (a deliberate deviation from the "install latest" convention
 * — ADR-0005); the deferred drift test (#4) reuses it to diff against real
 * `archgate init`.
 */
export { ARCHGATE_VERSION };

/** `npm install --save-dev` spec for the pinned archgate Dependency. */
export const ARCHGATE_DEP = `archgate@${ARCHGATE_VERSION}`;

/**
 * Seeded `.archgate/config.json`. Empty `domains` — the five ADR domains
 * (ARCH/BE/DATA/FE/GEN) are archgate built-ins available with zero config — and
 * a static `origin/main` base branch. Detection of the actual base branch is
 * deliberately not reintroduced at apply time (ADR-0005 / #5 out of scope). A
 * Seeded config file: written only when absent, never clobbered.
 */
export const archgateConfig = (): string => `${JSON.stringify({ domains: {}, baseBranch: 'origin/main' }, null, 2)}\n`;

/**
 * Seeded `.claude/settings.local.json`: archgate's Claude settings verbatim —
 * the `archgate:developer` agent plus the allowed archgate skills. Wires the
 * editor to archgate's agent/skills once the developer runs `archgate plugin
 * install`; inert until then. A Seeded config file (write-if-absent) so a
 * developer's own agent/permission customisations survive a re-run.
 */
export const claudeSettingsLocal = (): string =>
  `${JSON.stringify(
    {
      agent: 'archgate:developer',
      permissions: {
        allow: ['Skill(archgate:architect)', 'Skill(archgate:quality-manager)', 'Skill(archgate:adr-author)'],
        deny: [],
      },
    },
    null,
    2,
  )}\n`;

/**
 * The CLI's own copy of GEN-003's built-in default `markdown.frontmatter`
 * block — the four root-or-specific entries the Frontmatter Contract applies
 * when no config file is present. Seeding writes exactly this, so the seed is a
 * **behaviour no-op**: it materialises the policy GEN-003 already enforces by
 * default (ADR-0010 §6). GEN-003's rules.ts hardcodes the same block and cannot
 * import it (archgate rules share no runtime code), so this is a deliberate
 * second copy, kept honest by a shared-fixture test: both this copy and
 * GEN-003's are pinned to `DEFAULT_FRONTMATTER` in `harness-config-fixtures.ts`,
 * so a drift in either fails. Carries NONE of this repo's project-specific
 * entries (`docs/adr`, `docs/agents`, `.claude/agents`, `CONTEXT.md` — the #14
 * disambiguation, kept out of core).
 */
export const SEED_FRONTMATTER = {
  unmatched: 'exempt',
  pathRules: [
    { include: ['.archgate/adrs/*.md'], rule: { allowedTypes: ['adr'], label: 'title' } },
    { include: ['README.md'], rule: { allowedTypes: ['docs'], label: 'title' } },
    { include: ['AGENTS.md'], rule: { allowedTypes: ['agents-md'], label: 'title' } },
    { include: ['CLAUDE.md'], rule: { allowedTypes: ['claude-md'], label: 'title' } },
  ],
};

/**
 * Seeded `.typescript-ai-harness.json` (GEN-002 §1): the config envelope
 * stamping the harness release `version` over GEN-003's default frontmatter
 * block. A **Seeded** config file — written once, never patched on re-run; an
 * upgrade is the explicit migrate engine (#68), never a silent rewrite. The
 * stamp records which harness release wrote the config; GEN-002's `config-version`
 * equality-checks it only where `package.json` names the harness itself, so a
 * foreign Target carries the stamp without a mismatch. Two-space JSON with a
 * trailing newline so the file passes prettier on self-apply.
 */
export const harnessConfigSeed = (): string =>
  `${JSON.stringify({ version: HARNESS_VERSION, markdown: { frontmatter: SEED_FRONTMATTER } }, null, 2)}\n`;

/**
 * Append-only `.gitignore` entry for archgate's generated runtime. `rules.d.ts`
 * is `@generated` by `archgate check` (the first step of `verify`), so it is
 * only ignored here, never written. Comment matches archgate's own output to
 * keep the deferred drift test (#4) clean.
 */
export const RULES_DTS_IGNORE = ['# Archgate generated runtime (regenerated by archgate)', '.archgate/rules.d.ts'];
